server:
  host: ${SEVER_HOST}
  port: ${SEVER_PORT}
  netty:
    boss-count: 1
    worker-count: 1
    keep-alive: true
    backlog: 10

jwt:
  secret-key: ${SECRET_KEY}

web:
  client:
    baseurl : ${BASE_URL}
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
